project_id = "kcwcxnfxhvjujmticuwv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:8080"
additional_redirect_urls = ["http://localhost:8080", "http://127.0.0.1:8080"]

[functions.inviter-membre]
verify_jwt = false

[functions.dispatch-livraison]
verify_jwt = false

[functions.estimer-tarifs-ikms]
verify_jwt = true

[functions.zones-ikms]
verify_jwt = false

[functions.valider-panier-ikms]
verify_jwt = true

[functions.sync-livraisons]
verify_jwt = false

[functions.paiement-webhook]
verify_jwt = false
